### ISSUE TITLE
What is prospect for Landlock?

### ISSUE THREAD

**Issue by vt-alt** [landlock-lsm/landlock-lsm.github.io#1]
Is it intended for inclusion into Linux upstream eventually, or just to be forever independent patch set?

Thanks

**Comment by l0kod** [comment]
I'm actively working on upstreaming Landlock: https://lore.kernel.org/lkml/20201209192839.1396820-1-mic@digikod.net/

There is no point in keeping an independand patchset. You can follow the progress on https://landlock.io/

**Comment by vt-alt** [comment]
Thanks for the answer!
