### ISSUE TITLE
Does landlock support BPF

### ISSUE THREAD

**Issue by leiqi96** [landlock-lsm/landlock-lsm.github.io#3]
From this link https://landlock.io/#summary-2019-landlock-a-new-kind-of-linux-security-module-leveraging-ebpf,
it means that landlock  support bpf, but I can not find any bpf code in linux kernel https://github.com/torvalds/linux/tree/master/security/landlock.

If landlock supports bpf，Where can I find this code？

**Comment by l0kod** [comment]
As explained in the [warning section](https://landlock.io/#archives) just above: "Landlock is not based on eBPF anymore. These talks are outdated but kept for reference."

**Comment by leiqi96** [comment]
> As explained in the [warning section](https://landlock.io/#archives) just above: "Landlock is not based on eBPF anymore. These talks are outdated but kept for reference."

Can you help explain why you stopped using ebpf?

**Comment by l0kod** [comment]
It is explained in the Linux Security Summit talk (2021-09-29) page 12 (with links): "Why no more eBPF?"

* eBPF is very powerful and can be leveraged by attackers against the kernel (e.g., verifier bugs, Spectre): eBPF is not meant to be used by unprivileged users anymore.
* Programmable interface with I/O (e.g., maps) can lead to sidechannel attacks against other programs.
* Not possible to efficiently compose (loaded) programs (i.e., only stack them).
