### ISSUE TITLE
question about ruleset and rule.

### ISSUE THREAD

**Issue by leiqi96** [landlock-lsm/landlock-lsm.github.io#4]
hello,
From website https://www.kernel.org/doc/html/latest/userspace-api/landlock.html, 

it said that "**We first need to define the ruleset that will contain our rules. For this example, the ruleset will contain rules that only allow read actions, but write actions will be denied. The ruleset then needs to handle both of these kind of actions**".

Can I interpret this sentence in this way?

the **fs_access_masks** of ruleset is the default allow action，the rule is the  fine-grained rules.

when a process opens a file, landlock enforces  the  fine-grained rules. If there are no rules to match in the fine-grained rules， the default police(**fs_access_masks** of ruleset) is executed.

If the above is right，is the below LANDLOCK_ACCESS_FS_WRITE_FILE  of ruleset_attr  to be removed.

```
struct landlock_ruleset_attr ruleset_attr = {
    .handled_access_fs =
        LANDLOCK_ACCESS_FS_EXECUTE |
        LANDLOCK_ACCESS_FS_WRITE_FILE |    // here
        LANDLOCK_ACCESS_FS_READ_FILE |
        LANDLOCK_ACCESS_FS_READ_DIR |
        LANDLOCK_ACCESS_FS_REMOVE_DIR |
        LANDLOCK_ACCESS_FS_REMOVE_FILE |
        LANDLOCK_ACCESS_FS_MAKE_CHAR |
        LANDLOCK_ACCESS_FS_MAKE_DIR |
        LANDLOCK_ACCESS_FS_MAKE_REG |
        LANDLOCK_ACCESS_FS_MAKE_SOCK |
        LANDLOCK_ACCESS_FS_MAKE_FIFO |
        LANDLOCK_ACCESS_FS_MAKE_BLOCK |
        LANDLOCK_ACCESS_FS_MAKE_SYM |
        LANDLOCK_ACCESS_FS_REFER,
};
```

If not, How to understand the **fs_access_masks**  of ruleset and rule?
thanks.

**Comment by leiqi96** [comment]
another question:

If a rule ("/home/a.txt" , "rw") is for process P1 and P2 is a child process of P1,
Can P2 set a new rule("/home/a.txt", "ro")



If a rule ("/home/a.txt" , "ro") is for process P1 and P2 is a child process of P1,
Can P2 set a new rule("/home/a.txt", "rw")

**Comment by l0kod** [comment]
This repository is not intended for questions and discussions. Could you please send these questions to landlock@lists.linux.dev ?
